### ISSUE TITLE
unexpected behaviour scaling values by default

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata-plot#147] opened 2023-08-28 15:06 UTC
Just tried to plot a custom dataset:
```python
sdatas["ht232p1h1a2"].table[:,"TNFRSF4"].X.max()
>>> 2.4870176
```

I expect the colorbar to go from 0 to the max value, instead it goes to 1
```python
sdatas["ht232p1h1a2"].pl.render_shapes(color="TNFRSF4", layer="X").pl.show()
```
![image](https://github.com/scverse/spatialdata-plot/assets/25887487/390a69e7-0dfa-4c3c-bf8b-26f230dfa079)

while there is value in scaling it, it shouldn't be the default as it prevent from being able to compare across variables

**Comment by giovp** [comment] 2023-08-28 15:10
probably related to #132

**Comment by timtreis** [comment] 2023-08-29 15:44
Yeah, duplicate of https://github.com/scverse/spatialdata-plot/issues/132

**Closed by timtreis** 2023-08-29 15:44 UTC
